/// DTO for creating a new tag.
///
/// Contains only the fields necessary for tag creation.
/// The id is generated by the database, and audit fields are auto-managed.
class TagCreate {
  /// Tag name (required).
  final String name;

  /// Optional description.
  final String? description;

  /// Optional hex color (e.g., '#FF5722').
  final String? color;

  /// Creates a TagCreate DTO.
  const TagCreate({
    required this.name,
    this.description,
    this.color,
  });

  /// Business validation - checks if the data is valid for creation.
  bool get isValid => name.isNotEmpty;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagCreate &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          color == other.color;

  @override
  int get hashCode => Object.hash(name, description, color);

  @override
  String toString() => 'TagCreate(name: $name)';
}
