# build.yaml
targets:
  $default:
    sources:
      - bin/**
      - lib/**
      - test/**
      # - $package$
    builders:
      reflectable_builder:reflectable_builder:
        generate_for:
          - bin/server.dart
        options:
          formatted: true
          # Não funcionou
          # target: "server.g.dart"
      envied_generator|envied:
        generate_for:
          - lib/config/env/**.dart
        options:
          # path: .env.custom
          override: true
      drift_dev:
        options:
          store_date_time_values_as_text: true
          sql:
            dialects:
              - postgres
