###
https://ems.local/api/v1

###
https://ems.local/api/v1/health

###
https://ems.local/api/v1/users

###
https://ems.local/api/v1/docs/openapi.json

###
https://ems.local/api/v1/docs

###
https://ems.local/api/v1/areas
