import 'package:core_shared/core_shared.dart';
import 'tag.dart';

/// TagDetails entity with persistence metadata.
///
/// This class aggregates the pure domain entity [Tag] with
/// persistence fields defined by [BaseDetails]. It's used for
/// data transfer between repository and use case layers.
///
/// IMPORTANT: All fields from [BaseDetails] are required and non-nullable
/// (except createdAt/updatedAt which are DateTime, not DateTime?).
/// This aligns with DriftTableMixinPostgres which defines
/// withDefault(CURRENT_TIMESTAMP) for timestamp fields.
class TagDetails implements BaseDetails {
  /// Unique identifier (UUID generated by database).
  @override
  final String id;

  /// Soft delete flag.
  @override
  final bool isDeleted;

  /// Active status flag.
  @override
  final bool isActive;

  /// Creation timestamp (non-nullable - auto-generated by DB).
  @override
  final DateTime createdAt;

  /// Last update timestamp (non-nullable - auto-updated by DB).
  @override
  final DateTime updatedAt;

  /// Pure domain entity.
  final Tag data;

  /// Usage counter - how many times this tag is being used.
  final int usageCount;

  /// Creates a TagDetails instance.
  TagDetails({
    required this.id,
    this.isDeleted = false,
    this.isActive = true,
    required this.createdAt,
    required this.updatedAt,
    required String name,
    String? description,
    String? color,
    this.usageCount = 0,
  }) : data = Tag(
         name: name,
         description: description,
         color: color,
       );

  // Convenience getters to access domain fields

  /// Tag name.
  String get name => data.name;

  /// Tag description.
  String? get description => data.description;

  /// Tag color (hex).
  String? get color => data.color;

  /// Whether this tag is being used.
  bool get isUsed => usageCount > 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagDetails && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() =>
      'TagDetails(id: $id, name: $name, usageCount: $usageCount)';
}
