# Configurações de análise estática para pacote Flutter (UI)
# Este arquivo DEVE incluir as regras centralizadas da raiz do monorepo

include: ../../../analysis_options_flutter.yaml
# Customizações específicas deste pacote (se necessário)
# linter:
#   rules:
#     # Adicionar regras extras aqui
